"""initial_migration

Revision ID: 80b274a40fa7
Revises: 
Create Date: 2026-09-16 03:00:29.058616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '80b274a40fa7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_system', sa.String(length=30), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('keycloak_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('OFFICER','ADMIN','BIDDER','VIGILANCE')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('keycloak_sub')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('bidders',
    sa.Column('legal_name', sa.String(length=300), nullable=False),
    sa.Column('pan_number', sa.Text(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('udyam_number', sa.String(length=30), nullable=True),
    sa.Column('cin', sa.String(length=30), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pan_number')
    )
    op.create_index(op.f('ix_bidders_user_id'), 'bidders', ['user_id'], unique=False)
    op.create_table('eligibility_rule_sets',
    sa.Column('tender_category', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('scoring_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_rule_sets_created_by'), 'eligibility_rule_sets', ['created_by'], unique=False)
    op.create_table('eligibility_rules',
    sa.Column('rule_set_id', sa.Uuid(), nullable=False),
    sa.Column('check_type_id', sa.Uuid(), nullable=False),
    sa.Column('condition', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('severity_if_fail', sa.String(length=10), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['check_type_id'], ['check_types.id'], ),
    sa.ForeignKeyConstraint(['rule_set_id'], ['eligibility_rule_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_rules_check_type_id'), 'eligibility_rules', ['check_type_id'], unique=False)
    op.create_index(op.f('ix_eligibility_rules_rule_set_id'), 'eligibility_rules', ['rule_set_id'], unique=False)
    op.create_index('uq_rule_check', 'eligibility_rules', ['rule_set_id', 'check_type_id'], unique=True)
    op.create_table('tenders',
    sa.Column('gem_bid_number', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('eligibility_rule_set_id', sa.Uuid(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['eligibility_rule_set_id'], ['eligibility_rule_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gem_bid_number')
    )
    op.create_index(op.f('ix_tenders_closing_date'), 'tenders', ['closing_date'], unique=False)
    op.create_index(op.f('ix_tenders_created_by'), 'tenders', ['created_by'], unique=False)
    op.create_table('bid_applications',
    sa.Column('bidder_id', sa.Uuid(), nullable=False),
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rule_set_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('intake_pending','intake_complete','processing','ready_for_review','closed','reopened')"),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.ForeignKeyConstraint(['rule_set_id'], ['eligibility_rule_sets.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_applications_bidder_id'), 'bid_applications', ['bidder_id'], unique=False)
    op.create_index(op.f('ix_bid_applications_status'), 'bid_applications', ['status'], unique=False)
    op.create_index(op.f('ix_bid_applications_tender_id'), 'bid_applications', ['tender_id'], unique=False)
    op.create_index('uq_active_application', 'bid_applications', ['bidder_id', 'tender_id'], unique=True, postgresql_where=sa.text("status != 'closed'"))
    op.create_table('tender_officers',
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('officer_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('tender_id', 'officer_id')
    )
    op.create_index(op.f('ix_tender_officers_officer_id'), 'tender_officers', ['officer_id'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('suggested_action', sa.String(length=30), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['bid_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_application_id'), 'ai_recommendations', ['application_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('before_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('after_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('prev_event_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['bid_applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash')
    )
    op.create_index('ix_audit_case_time', 'audit_events', ['application_id', 'event_at'], unique=False)
    op.create_index(op.f('ix_audit_events_application_id'), 'audit_events', ['application_id'], unique=False)
    op.create_index('uq_audit_successor', 'audit_events', ['application_id', 'prev_event_hash'], unique=True)
    op.create_table('compliance_checks',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('check_type_id', sa.Uuid(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("result IN ('pass','fail','pending','not_evaluated')"),
    sa.CheckConstraint("source != 'AI_ANOMALY' OR evidence IS NOT NULL"),
    sa.ForeignKeyConstraint(['application_id'], ['bid_applications.id'], ),
    sa.ForeignKeyConstraint(['check_type_id'], ['check_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_application_id'), 'compliance_checks', ['application_id'], unique=False)
    op.create_index(op.f('ix_compliance_checks_check_type_id'), 'compliance_checks', ['check_type_id'], unique=False)
    op.create_table('compliance_scores',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('score_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('overall_score BETWEEN 0 AND 100'),
    sa.ForeignKeyConstraint(['application_id'], ['bid_applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('decisions',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('officer_id', sa.Uuid(), nullable=False),
    sa.Column('decision_value', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('overrode_ai_recommendation', sa.Boolean(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("decision_value IN ('qualify','disqualify','request_more_info')"),
    sa.CheckConstraint('NOT overrode_ai_recommendation OR length(trim(remarks)) >= 10'),
    sa.ForeignKeyConstraint(['application_id'], ['bid_applications.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_application_id'), 'decisions', ['application_id'], unique=False)
    op.create_table('documents',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('extraction_status', sa.String(length=30), nullable=False),
    sa.Column('extracted_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['bid_applications.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_application_id'), 'documents', ['application_id'], unique=False)
    op.create_index('uq_document_version', 'documents', ['application_id', 'doc_type', 'version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_document_version', table_name='documents')
    op.drop_index(op.f('ix_documents_application_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_decisions_application_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('compliance_scores')
    op.drop_index(op.f('ix_compliance_checks_check_type_id'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_application_id'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_index('uq_audit_successor', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_application_id'), table_name='audit_events')
    op.drop_index('ix_audit_case_time', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_ai_recommendations_application_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_tender_officers_officer_id'), table_name='tender_officers')
    op.drop_table('tender_officers')
    op.drop_index('uq_active_application', table_name='bid_applications', postgresql_where=sa.text("status != 'closed'"))
    op.drop_index(op.f('ix_bid_applications_tender_id'), table_name='bid_applications')
    op.drop_index(op.f('ix_bid_applications_status'), table_name='bid_applications')
    op.drop_index(op.f('ix_bid_applications_bidder_id'), table_name='bid_applications')
    op.drop_table('bid_applications')
    op.drop_index(op.f('ix_tenders_created_by'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_closing_date'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index('uq_rule_check', table_name='eligibility_rules')
    op.drop_index(op.f('ix_eligibility_rules_rule_set_id'), table_name='eligibility_rules')
    op.drop_index(op.f('ix_eligibility_rules_check_type_id'), table_name='eligibility_rules')
    op.drop_table('eligibility_rules')
    op.drop_index(op.f('ix_eligibility_rule_sets_created_by'), table_name='eligibility_rule_sets')
    op.drop_table('eligibility_rule_sets')
    op.drop_index(op.f('ix_bidders_user_id'), table_name='bidders')
    op.drop_table('bidders')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_table('check_types')
    # ### end Alembic commands ###
