"""add index on created_at and id for bid_applications

Revision ID: e0508d3b614c
Revises: 80b274a40fa7
Create Date: 2026-09-16 09:13:45.839280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0508d3b614c'
down_revision: Union[str, Sequence[str], None] = '80b274a40fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bid_applications_created_at_id', 'bid_applications', ['created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bid_applications_created_at_id', table_name='bid_applications')
    # ### end Alembic commands ###
